### ISSUE TITLE
[Bounty] Token creation not working - No error shown

### ISSUE THREAD

**Issue by shanadas** [Rovak/wallet-web#183]
Could not create tokens. No error is displayed. Just that it doesn't get created.

**Comment by lazarovicedo** [comment]
This is the error on the console:

google-protobuf.js:98 Uncaught (in promise) goog.asserts.AssertionError {message: "Assertion failed", reportErrorToServer: true, messagePattern: "Assertion failed", stack: "AssertionError: Assertion failed↵    at new goog.a…tronscan.org/static/js/main.c22ea9c5.js:55810:23)"}

**Comment by peel3r** [comment]
same for me: `VM71:21 Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build
    at <anonymous>:21:35
(anonymous) @ VM71:21
google-protobuf.js:98 Uncaught (in promise) goog.asserts.AssertionErrormessage: "Assertion failed"messagePattern: "Assertion failed"reportErrorToServer: truestack: "AssertionError: Assertion failed↵    at new goog.asserts.AssertionError (https://tronscan.org/static/js/main.c22ea9c5.js:26845:603)↵    at Object.goog.asserts.doAssertFailure_ (https://tronscan.org/static/js/main.c22ea9c5.js:26846:126)↵    at Object.goog.asserts.assert (https://tronscan.org/static/js/main.c22ea9c5.js:26846:385)↵    at jspb.BinaryReader.readEnum (https://tronscan.org/static/js/main.c22ea9c5.js:27101:398)↵    at proto.protocol.Transaction.raw.deserializeBinaryFromReader (https://tronscan.org/static/js/main.c22ea9c5.js:30177:86)↵    at jspb.BinaryReader.readMessage (https://tronscan.org/static/js/main.c22ea9c5.js:27092:329)↵    at Function.proto.protocol.Transaction.deserializeBinaryFromReader (https://tronscan.org/static/js/main.c22ea9c5.js:29623:14)↵    at Function.proto.protocol.Transaction.deserializeBinary (https://tronscan.org/static/js/main.c22ea9c5.js:29603:37)↵    at HttpClient.signTransaction (https://tronscan.org/static/js/main.c22ea9c5.js:55749:35)↵    at HttpClient.createToken (https://tronscan.org/static/js/main.c22ea9c5.js:55810:23)"__proto__: goog.debug.Error`
