### ISSUE TITLE
yarn start: "Command Failed

### ISSUE THREAD

**Issue by bondibox** [Rovak/wallet-web#44]
Launched wallet-web via command "yarn start"
Expected a webserver to launch on port 3000
Actual:

Killed
error An unexpected error occurred: "Command failed.
Exit code: 137
Command: sh
Arguments: -c node scripts/start.js
Directory: /root/wallet-web
Output:
".

======================================
Last lines of Error.log
  Output:
  
      at ProcessTermError.Error (native)
      at ProcessTermError.MessageError (/usr/lib/node_modules/yarn/lib/cli.js:186:110)
      at new ProcessTermError (/usr/lib/node_modules/yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:30281:17)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

Yarn version:   1.5.1
Node version:  9.11.1
Platform:  linux x64

I tried two different yarn installations, one with npm and the other with apt

**Comment by bondibox** [comment]
Yes I see. One must first install yarn before downloading the wallet-web.
